<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected  $guarded = ['id']; //to make all attributes assignable

    protected $with = ['category','user'];

    protected  $fillable = ['title','slug','excerpt','body','user_id','category_id']; // to declare only the assignable attributes

    public function getRouteKeyName()
    {
        return 'slug';   // TODO: Change the autogenerated stub
    }

    public function category(){
        return $this->belongsTo(Category::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

}
